export default {
    // Port nextjs runs on during development
    nextPort: 3000,
    // Url your app runs on during production
    appUrl: "$appID",
    // List of pages used by the nativeforge page generator and sets the native navigation paths
    pages: {
        home: ""
    },
    // List of features generated by nativeforge
    features: []
}