export default {
    // Port nextjs runs on during development
    nextPort: 3000,
    // Url your app runs on during production
    appUrl: "$appID",
    // List of pages used by the nativeforge page generator
    pages: ["Home"],
    // List of features generated by nativeforge
    features: []
}